# Generated by Django 4.0.10 on 2024-01-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='code',
            new_name='reset_code',
        ),
    ]
