# Generated by Django 4.0.10 on 2024-02-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_review_user_review_giver_review_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
