# Generated by Django 4.0.10 on 2024-02-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_review_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
