# Generated by Django 4.0.10 on 2024-03-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_pickedup'),
        ('users', '0011_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_posts',
            field=models.ManyToManyField(related_name='saved_by_users', to='products.product'),
        ),
    ]
