# Generated by Django 4.0.10 on 2024-03-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_pickedup'),
        ('users', '0013_alter_user_saved_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='products.product'),
        ),
    ]
