export const categoryIcons = {
  Italian: require("../../assets/icons/italian.png"),
  Vegan: require("../../assets/icons/vegetarian.png"),
  Meat: require("../../assets/icons/meat.png"),
  Asian: require("../../assets/icons/asian.png"),
  Mexican: require("../../assets/icons/mexican.png"),
  Produce: require("../../assets/icons/produce.png"),
  Desserts: require("../../assets/icons/dessert.png"),
  Canned: require("../../assets/icons/canned.png"),
};

export const foodListings = [
  {
    dish: "Pasta Carbonara",
    name: "Aisha",
    date: "3 hours ago",
    image: require("../../assets/images/dummyImages/Pasta.jpg"),
    category: "Italian",
    distance: "1km",
    rating: 4.5,
    allergen: ["Wheat", "Eggs", "Cheese"],
  },
  {
    dish: "Veggie Pizza",
    name: "Daniel",
    date: "5 hours ago",
    image: require("../../assets/images/dummyImages/Pizza.webp"),
    category: "Italian",
    distance: "2km",
    rating: 3.5,
  },
  {
    dish: "Grilled Chicken",
    name: "Olga",
    date: "1 hours ago",
    image: require("../../assets/images/dummyImages/Chicken.jpg"),
    category: "Meat",
    distance: "4km",
    rating: 5,
  },
  {
    dish: "Vegan Burrito",
    name: "Giovanni",
    date: "8 hours ago",
    image: require("../../assets/images/dummyImages/Burrito.jpg"),
    category: ["Mexican", "Vegan"],
    distance: "6km",
    rating: 3,
  },
  {
    dish: "Cheeseburger",
    name: "Linh",
    date: "4 hours ago",
    image: require("../../assets/images/dummyImages/Cheeseburger.jpg"),
    category: "Meat",
    distance: "9km",
    rating: 1.5,
    allergen: ["Cheese"],
  },
  {
    dish: "Rice Noodles",
    name: "Esmeralda",
    date: "5 hours ago",
    image: require("../../assets/images/dummyImages/Ricenoodles.webp"),
    category: "Asian",
    distance: "9km",
    rating: 2.5,
  },
  {
    dish: "BBQ Ribs",
    name: "Haruki",
    date: "7 hours ago",
    image: require("../../assets/images/dummyImages/Bbqribs.jpg"),
    category: "Meat",
    distance: "11km",
    rating: 4.7,
  },
  {
    dish: "Salmon Salad",
    name: "Kwame",
    date: "1 day ago",
    image: require("../../assets/images/dummyImages/Salmonsalad.jpeg"),
    category: "Meat",
    distance: "8km",
    rating: 4.9,
  },
  {
    dish: "Vegan Sushi",
    name: "Francesca",
    image: require("../../assets/images/dummyImages/VeganSushi.jpg"),
    category: ["Asian", "Vegan"],
    distance: "10km",
    rating: 3.9,
  },
  {
    dish: "Spaghetti Bolognese",
    name: "Ananya",
    date: "1 day ago",
    image: require("../../assets/images/dummyImages/Spaghettibolognese.jpg"),
    category: ["Italian", "Meat"],
    distance: "12km",
    rating: 1.8,
    allergen: ["Tree nuts"],
  },
  {
    dish: "Lobster Bisque",
    name: "Michael",
    date: "1 day ago",
    image: require("../../assets/images/dummyImages/LobsterBisque.png"),
    category: "Seafood",
    distance: "1km",
    rating: 1.8,
    allergen: ["Seafood"],
  },
  {
    dish: "Mushroom Risotto",
    name: "Pierre",
    date: "1 day ago",
    image: require("../../assets/images/dummyImages/MushroomRisotto.jpg"),
    category: ["Italian"],
    distance: "8km",
    rating: 4.5,
  },
];

// Exporting sort options if needed elsewhere
export const sortOptions = [
  { label: "Distance", value: "Distance" },
  { label: "Rating", value: "Rating" },
  { label: "Date", value: "Date" },
];
