export const foodListings = [
  {
    title: "Pasta Carbonara",
    owner: "Aisha",
    date: "3 hours ago",
    //image: require("../../assets/images/postImages/image_0_fPMr83c.jpg"),
    image: require("../../assets/images/dummyImages/Pizza.webp"),
    categories: "Italian",
    distance: "1km",
    rating: 4.5,
    allergens: ["Wheat", "Eggs", "Cheese"],
  },
  {
    title: "Veggie Pizza",
    owner: "Daniel",
    date: "5 hours ago",
    image: require("../../assets/images/dummyImages/Pizza.webp"),
    categories: "Italian",
    distance: "2km",
    rating: 3.5,
  },
  {
    title: "Grilled Chicken",
    owner: "Olga",
    date: "1 hours ago",
    image: require("../../assets/images/dummyImages/Chicken.jpg"),
    categories: "Meat",
    distance: "4km",
    rating: 5,
  },
  {
    title: "Vegan Burrito",
    owner: "Giovanni",
    date: "8 hours ago",
    image: require("../../assets/images/dummyImages/Burrito.jpg"),
    categories: ["Mexican", "Vegan"],
    distance: "6km",
    rating: 3,
  },
  {
    title: "Cheeseburger",
    owner: "Linh",
    date: "4 hours ago",
    image: require("../../assets/images/dummyImages/Cheeseburger.jpg"),
    categories: "Meat",
    distance: "9km",
    rating: 1.5,
    allergens: ["Cheese"],
  },
  {
    title: "Rice Noodles",
    owner: "Esmeralda",
    date: "5 hours ago",
    image: require("../../assets/images/dummyImages/Ricenoodles.webp"),
    categories: "Asian",
    distance: "9km",
    rating: 2.5,
  },
  {
    title: "BBQ Ribs",
    owner: "Haruki",
    date: "7 hours ago",
    image: require("../../assets/images/dummyImages/Bbqribs.jpg"),
    categories: "Meat",
    distance: "11km",
    rating: 4.7,
  },
  {
    title: "Salmon Salad",
    owner: "Kwame",
    date: "1 day ago",
    image: require("../../assets/images/dummyImages/Salmonsalad.jpeg"),
    categories: "Meat",
    distance: "8km",
    rating: 4.9,
  },
  {
    title: "Vegan Sushi",
    owner: "Francesca",
    image: require("../../assets/images/dummyImages/VeganSushi.jpg"),
    categories: ["Asian", "Vegan"],
    distance: "10km",
    rating: 3.9,
  },
  {
    title: "Spaghetti Bolognese",
    owner: "Ananya",
    date: "1 day ago",
    image: require("../../assets/images/dummyImages/Spaghettibolognese.jpg"),
    categories: ["Italian", "Meat"],
    distance: "12km",
    rating: 1.8,
    allergens: ["Tree nuts"],
  },
  {
    title: "Lobster Bisque",
    owner: "Michael",
    date: "1 day ago",
    image: require("../../assets/images/dummyImages/LobsterBisque.png"),
    categories: "Seafood",
    distance: "1km",
    rating: 1.8,
    allergens: ["Seafood"],
  },
  {
    title: "Mushroom Risotto",
    owner: "Pierre",
    date: "1 day ago",
    image: require("../../assets/images/dummyImages/MushroomRisotto.jpg"),
    categories: ["Italian"],
    distance: "8km",
    rating: 4.5,
  },
];

export const sortOptions = [
  {
    label: "Distance",
    value: "Distance",
    icon: require("../../assets/distance.png"),
  },
  {
    label: "Rating",
    value: "Rating",
    icon: require("../../assets/star.png"),
  },
  { label: "Date", value: "Date", icon: require("../../assets/date.png") },
];
