# Generated by Django 4.0.10 on 2024-03-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_pickedup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
