# Generated by Django 4.0.10 on 2024-03-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_latitude_product_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='postalcode',
            field=models.CharField(default='V1V 1V7', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
