# Generated by Django 4.0.10 on 2024-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_postalcode_alter_product_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='postalcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
