import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "white",
    paddingTop: 20,
    paddingBottom: 20,
  },
  input: {
    width: "90%",
    padding: 15,
    marginVertical: 10,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    borderColor: "#CCCCCC",
    borderWidth: 1,
  },
  label: {
    alignSelf: "flex-start",
    marginLeft: "5%",
    marginTop: 10,
    marginBottom: 5,
    fontWeight: "bold",
    fontSize: 16,
  },
  toggleButton: {
    marginHorizontal: 10,
    marginBottom: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: "#007AFF",
    borderRadius: 20,
  },
  imagePreview: {
    height: 300,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 30,
    borderColor: "#CCCCCC",
    borderWidth: 1,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  placeholderText: {
    color: "#999999",
    fontSize: 16,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
  },
  button: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 10,
    marginVertical: 10,
    backgroundColor: "#007AFF",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 3,
  },
  buttonText: {
    color: "white",
    textAlign: "center",
    fontSize: 16,
  },
  saveButton: {
    backgroundColor: "orange",
  },
  
});
