# Generated by Django 4.2.6 on 2023-10-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
    ]
